<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>fhem.cfg</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#.*FHEM.*</string>
	<key>name</key>
	<string>FHEM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(fhem)\b</string>
			<key>name</key>
			<string>keyword.definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fhem</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.documentation.fhem</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.definition</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.module</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(define)\s+([-a-zA-Z0-9_.]+)\s*([-a-zA-Z0-9_.]+)?</string>
			<key>name</key>
			<string>meta.function.fhem.define</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.module</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(attr)\s+([-a-zA-Z0-9_.]+)\s*([-a-zA-Z0-9_.]+)?</string>
			<key>name</key>
			<string>meta.function.fhem.attr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fhem.cfg</string>
	<key>uuid</key>
	<string>E307B812-A029-43AF-8387-59FA001F469D</string>
</dict>
</plist>
