#!/bin/bash

#set -x
set -e # required by lintian
set +e # Don't know how to check presence of fhem in passwd with -e

if grep -q fhem /etc/passwd; then
    userdel fhem
fi

if test -f /etc/init/fhem.conf; then
    rm /etc/init/fhem.conf
fi

if test -f /etc/systemd/system/fhem.service; then
    rm /etc/systemd/system/fhem.service
fi
