#!/bin/sh

set -e

if grep -q fhem /etc/passwd; then
    userdel fhem
fi

if test -f /etc/init/fhem.conf; then
    rm /etc/init/fhem.conf
fi
if test -f /etc/init.d/fhem; then
    update-rc.d fhem remove
    rm /etc/init.d/fhem
fi
