#!/bin/bash
# $Id:$

set -e

# detect init system
test=$(stat /sbin/init |grep "File")
re="systemd$"

if [[ $test =~ $re ]]; then
   systemctl stop fhem.service
   systemctl disable fhem.service
else
   if test -f /etc/init.d/fhem; then
      /etc/init.d/fhem stop noaptmark
   fi
   update-rc.d fhem remove
fi
