#!/bin/sh

fw=$1
if test ! -f ../../$fw.tar.gz; then
  echo "usage: makeimage <fhem-VERSION>"
  echo "../../<fhem-VERSION>.tar.gz must exist"
  exit 1
fi

rm -rf var
echo Extracting the fritzbox template
tar xf ../../priv/fritzbox7390_template.tar
cd var
tar zxf fhem.tar.gz
rm -rf fhem/FHEM fhem/www fhem/docs
mkdir fhem/FHEM fhem/docs
cd ..

cp install var
cp backup.sh startfhem* var/fhem
cp fhemcmd.sh var/fhem/FHEM


echo Extracting $fw
rm -rf $fw
tar zxf ../../$fw.tar.gz
cd $fw
cp fhem.cfg fhem.pl ../var/fhem
cp -rp FHEM/* ../var/fhem/FHEM
cp docs/*.html docs/*.jpg ../var/fhem/docs
cp -rp www ../var/fhem
cp -rp README_DEMO.txt fhem.cfg.demo demolog ../var/fhem
rm -rf ../var/fhem/www/frontend

cd ..
rm -rf $fw


echo Packing again
cd var
#cat >> fhem/fhem.cfg << EOF
#attr global backupcmd backup.sh
#EOF
tar cf - fhem | gzip -9 > fhem.tar.gz
rm -rf fhem

cd ..
tar cf $fw-fb7390.image var
rm -rf var
